apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-multitool-nfs
  template:
    metadata:
      labels:
        app: network-multitool-nfs
    spec:
      containers:
      - name: network-multitool-nfs
        image: wbitt/network-multitool
        command: ['sh', '-c', 'while true; do echo "Hello from NFS!" >> /mnt/nfs-shared/data.txt; sleep 5; done']
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/nfs-shared
          readOnly: false
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
