apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  #namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
