---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  #namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
