---
vector_version: "0.41.1"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"

vector_config:
  sinks:
    to_clickhouse:
      database: custom
      endpoint: http://89.169.159.239:8123
      healthcheck: false
      inputs:
      - our_log
      skip_unknown_fields: true
      table: my_table
      type: clickhouse
  sources:
    our_log:
      ignore_older_secs: 600
      include:
      - /home/dbn_usr/logs/*.log
      read_from: beginning
      type: file
