apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - name: nginx
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: network-multitool
    protocol: TCP
    port: 9002
    targetPort: 8080
  type: ClusterIP
